name: Manual Production Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project to deploy
        required: true
        default: both
        type: choice
        options:
          - api
          - frontend
          - both

permissions:
  contents: read

jobs:
  deploy-api:
    if: ${{ inputs.project == 'api' || inputs.project == 'both' }}
    runs-on: ubuntu-latest
    name: Deploy api to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, yaml
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Plan deployment
        run: ./shipper plan api --profile=production
        env:
          PLOI_API_KEY: ${{ secrets.PLOI_API_KEY }}

      - name: Deploy to production
        run: ./shipper apply api --profile=production --force
        env:
          PLOI_API_KEY: ${{ secrets.PLOI_API_KEY }}

  deploy-frontend:
    if: ${{ inputs.project == 'frontend' || inputs.project == 'both' }}
    runs-on: ubuntu-latest
    name: Deploy frontend to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, yaml
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Plan deployment
        run: ./shipper plan frontend --profile=production
        env:
          PLOI_API_KEY: ${{ secrets.PLOI_API_KEY }}

      - name: Deploy to production
        run: ./shipper apply frontend --profile=production --force
        env:
          PLOI_API_KEY: ${{ secrets.PLOI_API_KEY }}
